### ISSUE TITLE
Dissociate NSLocationAlwaysAndWhenInUse and NSLocationWhenInUse permission request

### ISSUE THREAD

**Issue by alex596** [once10301/permission#12]
Hello, it's possible to dissociate the location permissions request ( LocationAlways and LocationOnly) iOS ? For not request at the users the LocationAlways permission if no need. Thanks for your response.

**Comment by once10301** [comment]
I have add WhenInUse, if you want to request only Always in iOS11, delete the NSLocationAlwaysAndWhenInUseUsageDescription in info.plist
