### ISSUE TITLE
image_picker permission explicit  inandroid

### ISSUE THREAD

**Issue by trompetin17** [once10301/permission#20]
Hi, I want to share this strange behavior in android when you use image_picker.
This behavior happens the first time I use image_picker in a fresh install. the library ask about permission, but nothing happens even if you say "allow", I need to restart the app, and then everything works fine.

I already have External Storage permission in my android manifest. Also, I look up the source code and find something interesting here:

https://github.com/flutter/plugins/blob/afa2f0877a10c7f9f6898a0107da07d9ce90b670/packages/image_picker/android/src/main/java/io/flutter/plugins/imagepicker/ImagePickerDelegate.java#L194

It asks for permission and then codes returns and the flutter didn't receive any notice from the plugin.

**Comment by once10301** [comment]
I do not understand what you mean?

**Comment by once10301** [comment]
I think you went the wrong place.
image_picker is not my project.
