### ISSUE TITLE
Any idea about this error? cannot find symbol import android.support.v4.app.ActivityCompat;

### ISSUE THREAD

**Issue by wyxcoder** [once10301/permission#22]
C:\Tools\flutter\.pub-cache\hosted\pub.dartlang.org\permission-0.1.1\android\src\main\java\com\ly\permission\PermissionPlugin.java:10: error: cannot find symbol
import android.support.v4.app.ActivityCompat;
                             ^
  symbol:   class ActivityCompat
  location: package android.support.v4.app
C:\Tools\flutter\.pub-cache\hosted\pub.dartlang.org\permission-0.1.1\android\src\main\java\com\ly\permission\PermissionPlugin.java:11: error: package android.support.v4.content does not exist
import android.support.v4.content.ContextCompat;

**Comment by xspid3r** [comment]
Same problem here, i think it has something to do with **compileSdkVersion**

**Comment by k3v1n-uncle** [comment]
same problem

**Comment by devadrianapostol** [comment]
It's an AndroidX issue. I tried to fix it. Created pull request. 
You can use my fork.
https://github.com/devadrianapostol/permission

**Comment by marianoarga** [comment]
@devadrianapostol thank you very much

**Comment by ezraaaa** [comment]
@devadrianapostol how can i use your fork?

**Comment by marianoarga** [comment]
@ezraaaa Add in your pubspec.yaml:
```
permission:
    git:
      url: https://github.com/devadrianapostol/permission
```

**Comment by mikes222** [comment]
The fix is working. Please accept the pull request.

**Comment by once10301** [comment]
I have fixed it, can you try it again?

**Comment by ana-sher** [comment]
Same issue:(

**Comment by Pebsie** [comment]
Yep, issue is back.
