### ISSUE TITLE
Permission Error

### ISSUE THREAD

**Issue by tvqphong001** [once10301/permission#25]
package com.ly.permission;

import android.Manifest;
import android.app.Activity;
import android.content.Intent;
import android.content.pm.PackageManager;
import android.net.Uri;
import android.provider.Settings;

//import android.support.v4.app.ActivityCompat;  // this is your error
//import android.support.v4.content.ContextCompat; // this is your error

import androidx.core.app.ActivityCompat;  // this is i fix your bug
import androidx.core.content.ContextCompat;  // this is i fix your bug
import android.util.Log;

import java.util.ArrayList;
import java.util.List;

import io.flutter.plugin.common.MethodCall;
import io.flutter.plugin.common.MethodChannel;
import io.flutter.plugin.common.MethodChannel.MethodCallHandler;
import io.flutter.plugin.common.MethodChannel.Result;
import io.flutter.plugin.common.PluginRegistry;
import io.flutter.plugin.common.PluginRegistry.Registrar;

When i comment your code in import my app run succeed, but don't comment it will be error, please fix your bug or give me a solution, thanks!

**Comment by once10301** [comment]
I have fixed it, can you try it again?
