### ISSUE TITLE
Error: MissingPluginException(No implementation found for method getSinglePermissionStatus on channel plugins.ly.com/permission)

### ISSUE THREAD

**Issue by MawiraIke** [once10301/permission#28]
Got this error on Android 

Code:

```
var permissionStatus =
        await Permission.getSinglePermissionStatus(PermissionName.Storage);
    return permissionStatus;
```

**Comment by DerKapp** [comment]
Yeah I had the same issue. For Android you have to use the `getPermissionStatus` method and for IOS the `getSinglePermissionStatus`.. That's why I switched to  https://pub.dartlang.org/packages/permission_handler

**Comment by MawiraIke** [comment]
Thanks @Kappadona

**Comment by sanjayrajsinh** [comment]
I have the same issue, I also try this method still issue not solved  @Kappadona 

`Future<List<Permissions>> checkPermission() async {
    return await Permission.getPermissionsStatus([PermissionName.Storage]);
  }`

**Error** : MissingPluginException(No implementation found for method getPermissionsStatus on channel plugins.ly.com/permission)

**Comment by lifenautjoe** [comment]
Wow this plugin is horrible. Thanks for the heads up.

**Comment by XenonChau** [comment]
> Yeah I had the same issue. For Android you have to use the `getPermissionStatus` method and for IOS the `getSinglePermissionStatus`.. That's why I switched to https://pub.dartlang.org/packages/permission_handler

but there is a problem that no internet permission verification in this package.

**Comment by ahmarDebugger** [comment]
> > Yeah I had the same issue. For Android you have to use the `getPermissionStatus` method and for IOS the `getSinglePermissionStatus`.. That's why I switched to https://pub.dartlang.org/packages/permission_handler
> 
> but there is a problem that no internet permission verification in this package.

same issue
