### ISSUE TITLE
Not Working on Flutter 0.8.2 in IOS 12.0

### ISSUE THREAD

**Issue by digarahayu17** [once10301/permission#3]
hello there i already test this library, clear copy and paste like example but i got error like this i already add info.plist and android manifest

[VERBOSE-2:shell.cc(181)] Dart Error: Unhandled exception:
MissingPluginException(No implementation found for method requestPermissions on channel plugins.ly.com/permission)
#0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:278:7)
<asynchronous suspension>
#1      Permission.requestSinglePermission (package:permission/permission.dart:65:33)
<asynchronous suspension>
#2      _MyHomePageState.requestPermission (file:///Users/developer1/FLUTTER/enta/lib/main.dart:63:34)
<asynchronous suspension>
#3      _MyHomePageState._incrementCounter (file:///Users/developer1/FLUTTER/enta/lib/main.dart:51:5)
<asynchronous suspension>
#4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:503:14)
#5      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:558:30)
#6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
#7      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:242:9)
#8      TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:204:7)
#9      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
#10     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:147:20)
#11     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:121:22)
#12     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:101:7)
#13     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:64:7)
#14     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:48:7)
#15     _invoke1 (dart:ui/hooks.dart:142:13)
#16     _dispatchPointerDataPacket (dart:ui/hooks.dart:99:5)

**Comment by alexsauce** [comment]
I'm getting same errors for getPermissionStatus, requestPermisssions, openSettings, for all of them I get: No implementation found.

**Comment by ferbass** [comment]
just check the source code and the iOS part is not implemented :(

**Comment by emiliofonseca** [comment]
Same here

**Comment by once10301** [comment]
Please read the README.md
"A new flutter plugin for getting and requesting permission on Android."
on iOS  If you add info.plist, when you use this permission, there will be show a dialog to ask you.
