### ISSUE TITLE
Unable to compile Flutter project after installing the package

### ISSUE THREAD

**Issue by ramamurthyk** [once10301/permission#31]
I've created a Flutter project with Kotlin and Swift. I'm unable to build the project after using the permission package. Below is the build error?

Does it not support Flutter Kotlin / Swift project type?

C:\Dev\flutter\.pub-cache\hosted\pub.dartlang.org\permission-0.1.2\android\src\main\java\com\ly\permission\PermissionPlugin.java:10: error: package androidx.core.app does not exist
import androidx.core.app.ActivityCompat;
                        ^
C:\Dev\flutter\.pub-cache\hosted\pub.dartlang.org\permission-0.1.2\android\src\main\java\com\ly\permission\PermissionPlugin.java:11: error: package androidx.core.content does not exist
import androidx.core.content.ContextCompat;
                            ^
C:\Dev\flutter\.pub-cache\hosted\pub.dartlang.org\permission-0.1.2\android\src\main\java\com\ly\permission\PermissionPlugin.java:66: error: cannot find symbol
            if (ContextCompat.checkSelfPermission(registrar.activity(), permission) == PackageManager.PERMISSION_DENIED) {
                ^
  symbol:   variable ContextCompat
  location: class PermissionPlugin
C:\Dev\flutter\.pub-cache\hosted\pub.dartlang.org\permission-0.1.2\android\src\main\java\com\ly\permission\PermissionPlugin.java:67: error: cannot find symbol
                if (!ActivityCompat.shouldShowRequestPermissionRationale(activity, permission)) {
                     ^
  symbol:   variable ActivityCompat
  location: class PermissionPlugin
C:\Dev\flutter\.pub-cache\hosted\pub.dartlang.org\permission-0.1.2\android\src\main\java\com\ly\permission\PermissionPlugin.java:85: error: cannot find symbol
        ActivityCompat.requestPermissions(activity, permissions, 0);
        ^
  symbol:   variable ActivityCompat
  location: class PermissionPlugin
C:\Dev\flutter\.pub-cache\hosted\pub.dartlang.org\permission-0.1.2\android\src\main\java\com\ly\permission\PermissionPlugin.java:139: error: cannot find symbol
                    if (!ActivityCompat.shouldShowRequestPermissionRationale(registrar.activity(), strings[i])) {
                         ^
  symbol:   variable ActivityCompat
  location: class PermissionPlugin
6 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':permission:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s
*******************************************************************************************
The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
See https://goo.gl/CP92wY for more information on the problem and how to fix it.
*******************************************************************************************
Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

**Comment by RegiByte** [comment]
have you tried to add the following:

```
android.useAndroidX=true
```

to your `android/gradle.properties` file ? i've had a similar problem and it was solved by doing this

**Comment by DanialV** [comment]
same error here.

**Comment by thienvu18** [comment]
This is AndroidX compatible problem. Please take a look [here](https://flutter.dev/docs/development/packages-and-plugins/androidx-compatibility) to know how to migrate your Flutter app to AndroidX

**Comment by once10301** [comment]
AndroidX Support for New Apps
https://medium.com/flutter/announcing-flutter-1-7-9cab4f34eacf
