### ISSUE TITLE
standard permission pop up ONLY working in debug, and profile mode... NOT release mode

### ISSUE THREAD

**Issue by b-cancel** [once10301/permission#32]
if you want to test it on some button click run the code below

I really need the help, this is stopping me from progressing. 
I'm even willing to pay you if that's what it takes.

```
PermissionStatus startStatus = (await Permission.getPermissionsStatus([PermissionName.Contacts]))[0].permissionStatus;
print("start status: " + startStatus.toString());
Permission.requestPermissions([PermissionName.Contacts]);
```

**Comment by once10301** [comment]
Android or iOS?

**Comment by b-cancel** [comment]
@once10301 I personally am experiencing the problem on Android. 
After reading the information from the two links below...
https://flutter.dev/docs/testing/build-modes
https://github.com/flutter/flutter/wiki/Flutter's-modes

since the problem is only happening on release mode, it might be caused by a feature of release mode.

- Important code might be in an assertion. In release mode assertions are disabled, so this would cause a problem
- Important code might be within Debugging information. Since it is stripped out in release mode, that could cause a problem
- When Debugging is disabled something important might be disabled with it
- When the Compilation is optimized for fast startup, fast execution, and small package sizes something might have broken
- Or you might be using some Service extension which is disabled in release mode.

Hopefully, that helps you help all of us... This is the only permission package I could get to even work so you are my only hope...

Thanks again.

**Comment by once10301** [comment]
I run the example in release, It works fine.

**Comment by once10301** [comment]
Can you give me a project which has your problem?

**Comment by b-cancel** [comment]
@once10301 here is the project
I tried to make it as bare-bones as possible and the problem still persists
More Info comming soon
https://github.com/b-cancel/permissionTest

**Comment by b-cancel** [comment]
Flutter Doctor
[√] Flutter (Channel stable, v1.7.8+hotfix.3, on Microsoft Windows [Version 10.0.17134.885], locale en-US)
    • Flutter version 1.7.8+hotfix.3 at E:\CinE\Users\bryan\SOFTWARE\flutter
    • Framework revision b712a172f9 (12 days ago), 2019-07-09 13:14:38 -0700
    • Engine revision 54ad777fd2
    • Dart version 2.4.0

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\bryan\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: E:\CinE\Users\bryan\SOFTWARE\AndroidStudio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.3)
    • Android Studio at E:\CinE\Users\bryan\SOFTWARE\AndroidStudio
    • Flutter plugin version 33.4.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] Connected device (1 available)
    • SM G973U • R38M30EM6ME • android-arm64 • Android 9 (API 28)

• No issues found!

**Comment by b-cancel** [comment]
besides the files in the lib folder and the yaml file I also made changes to these files

not_at_home/android/app/src/profile/AndroidManifest.xml
not_at_home/android/app/src/debug/AndroidManifest.xml
not_at_home/android/app/src/main/AndroidManifest.xml

not_at_home/android/app/build.gradle
not_at_home/android/build.gradle

not_at_home/android/gradle.properties

**Comment by b-cancel** [comment]
I fixed my own problem...

you have to add the permissions in ALL of the AndroidManifest.xml files...

I just had to add this to each because I need to use the contacts plugin specifically
```
<!--For Contacts PlugIn-->
    <uses-permission android:name="android.permission.READ_CONTACTS"/>
    <uses-permission android:name="android.permission.WRITE_CONTACTS"/>
    <uses-permission android:name="android.permission.GET_ACCOUNTS"/>
```

**Comment by b-cancel** [comment]
@once10301 I suggest you addthis to the instructions of your plugin

in place of this
```
Make sure you add the needed permissions to your Android Manifest Permission.
```

place this
```
Make sure you add the needed permission to ALL of your Android Manifest Permission.
They can be found here
PROJECT_NAME/android/app/src/profile/AndroidManifest.xml
PROJECT_NAME/android/app/src/debug/AndroidManifest.xml
PROJECT_NAME/android/app/src/main/AndroidManifest.xml
```

Either way thanks for being so willing to help!
You have yourself a fantastic day!

**Comment by b-cancel** [comment]
hey @once10301 just letting you know that I ran into the problem again...
I copied everything over to a new project and the problem went away...
(referring to the same problem)
my guess is for anyone else having the same problem they might want to just run "flutter clean" 
copying everything over was too tedious

Hope that helps someone maybe
