### ISSUE TITLE
iOS Crash When Requesting Camera Permission

### ISSUE THREAD

**Issue by joshvocal** [once10301/permission#35]
Running this code: `await Permission.requestSinglePermission(PermissionName.Camera);` the app seems to crash with no error output.

Environment:
* iPhone XS 12.4 Emulator

Version:
*   permission: ^0.1.2

Notes:
* When getting the camera permission first before requesting the iOS camera permission, I get `PermissionStatus.notDecided`.

**Comment by thanhbinh84** [comment]
Cannot test camera on iOS emulator
