### ISSUE TITLE
unable to create folder and writing file only on andriod sdk 27 Oreo ?

### ISSUE THREAD

**Issue by iamprakash13** [once10301/permission#4]
i have requested permissions and allow permission request on oreo andriod and
i tried to create folder in the root of internalstorage using getExternalStorageDirectory() and Directory.create(). but folder is not created (no file access)
while this code works finely on other andriod versions below sdk 27.
using this permissions.dart in flutter

my flutter doctor:

```[!] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    X Android license status unknown.
[√] Android Studio (version 3.2)
[√] VS Code (version 1.29.1)
[√] VS Code, 64-bit edition (version 1.26.1)
[√] Connected device (1 available)
```

! Doctor found issues in 1 category. 
help me find solution
@iampawan @tensor-programming @PoojaB26

**Comment by elementzonline** [comment]
Hi, 
I am facing the same issue. How did you solve this

> i have requested permissions and allow permission request on oreo andriod and
> i tried to create folder in the root of internalstorage using getExternalStorageDirectory() and Directory.create(). but folder is not created (no file access)
> while this code works finely on other andriod versions below sdk 27.
> using this permissions.dart in flutter
> 
> my flutter doctor:
> 
> ```
>     X Android license status unknown.
> [√] Android Studio (version 3.2)
> [√] VS Code (version 1.29.1)
> [√] VS Code, 64-bit edition (version 1.26.1)
> [√] Connected device (1 available)
> ```
> 
> ! Doctor found issues in 1 category.
> help me find solution
> @iampawan @tensor-programming @PoojaB26

Hi, 
I am facing the same issue. How did you solve this
