### ISSUE TITLE
iOS - MissingPluginException(No implementation found for method getPermissionStatus )

### ISSUE THREAD

**Issue by mi0772** [once10301/permission#5]
Hi when this method will be implemented ?

thanks for your great work

**Comment by ppsdang** [comment]
I am facing the same issue

**Comment by apgapg** [comment]
The developer missd the implementation for singlepermission in andorid code. Use Permission.requestPermissions method and access the first element of the result

**Comment by once10301** [comment]
# Android
val permissions = await Permission.getPermissionStatus([PermissionName.Calendar, PermissionName.Camera]);

# iOS
val permissionStatus = await Permission.getSinglePermissionStatus(PermissionName.Calendar);

**Comment by once10301** [comment]
Multiple permissions can be applied together on Android, but only one permission can be applied on iOS.
